# Goi han bo nho toi da tren RAM
maxmemory 256mb

# Least recently used: khi bo nho dat toi 256mb, Redis se xoa key nao co TTL (Time to live) gan het han hoac it dung nhat
maxmemory-policy allkeys-lru

save ""
appendonly no

dir /data