version: '3.8'
services:
  db:
    image: postgres:17.10-alpine3.24
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: kienDz
      POSTGRES_DB: kienDb

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
